import { Food } from "./food";

export const foods: Food[] = [
  {
    id: "nasi-bakar",
    slug: "nasi-bakar",
    name: "Nasi Bakar",
    description: "Fragrant grilled rice, prepared fresh for a satisfying main course.",
    categoryId: "main-course",
    price: 19000,
    image: "/images/sticker tebunai.jpeg",
    enabled: true,
    sortOrder: 1,
  },
  {
    id: "nasi-sop-ayam",
    slug: "nasi-sop-ayam",
    name: "Nasi Sop Ayam",
    description: "Comforting chicken soup served with warm rice.",
    categoryId: "main-course",
    price: 19000,
    image: "/images/sticker tebunai.jpeg",
    enabled: true,
    sortOrder: 2,
  },
  {
    id: "risol-mayo",
    slug: "risol-mayo",
    name: "Risol Mayo",
    description: "Crisp risoles with a creamy mayonnaise filling.",
    categoryId: "snacks",
    price: 6000,
    image: "/images/sticker tebunai.jpeg",
    enabled: true,
    sortOrder: 1,
  },
  {
    id: "risol-sayur-rouguette",
    slug: "risol-sayur-rouguette",
    name: "Risol Sayur / Rouguette",
    description: "A savory vegetable risoles for a light, satisfying snack.",
    categoryId: "snacks",
    price: 6000,
    image: "/images/sticker tebunai.jpeg",
    enabled: true,
    sortOrder: 2,
  },
  {
    id: "sugarcane-rum-250ml",
    slug: "sugarcane-rum-250ml",
    name: "Sugarcane Rum",
    description: "Rum made from fermented and distilled sugarcane juice.",
    categoryId: "alcoholic-beverage",
    price: 50000,
    image: "/images/hero-bottle-v2.png",
    enabled: true,
    sortOrder: 1,
    volume: 250,
  },
];
